language: python
python:
- 3.7.9
install:
- pip install flask
script:
- python -m unittest -v test
deploy:
  provider: gae
  keyfile: "../gcpkey.json"
  project: labdevopscloud-ingrid
  on:
    branch: main
before_install:
- openssl aes-256-cbc -K $encrypted_28260de50144_key -iv $encrypted_28260de50144_iv
  -in gcpkey.json.enc -out ../gcpkey.json -d
